AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.2
  Exclude:
  - ".git/**/*"
  - "app/assets/**/*"
  - "bin/**/*"
  - "coverage/**/*"
  - "log/**/*"
  - "tmp/**/*"
  - "config/**/*"
  - "db/migrate/**/*"
  - "**/**/schema.rb"

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineEndStringConcatenationIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Lint/DuplicateBranch:
  IgnoreLiteralBranches: true

Metrics/ClassLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Metrics/ModuleLength:
  Max: 100

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: optional

Naming/MethodParameterName:
  AllowedNames: [as, at, by, db, id, in, io, ip, "on", to]

Naming/PredicateName:
  Enabled: true

Naming/VariableNumber:
  Enabled: true

Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: true

Style/RegexpLiteral:
  EnforcedStyle: mixed

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/SymbolArray:
  Enabled: true

Style/WordArray:
  Enabled: true

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
